---
services:
  app:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - OATHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ./config:/config
      - /mnt/public/eBooks:/books:rw
    ports:
      - 8083:8083

networks:
  default:
    driver: overlay
    external: true
    name: calibre
