services:
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - OATHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ./config:/config
      - /mnt/public/eBooks:/books:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre-web.rule=Host(`calibre-web.tyler-clark.com`)
      - traefik.http.routers.calibre-web.tls=true
      - traefik.http.routers.calibre-web.tls.certresolver=cloudflare

networks:
  default:
    name: frontend
    external: true
